[package]
name = "bit_store"
version = "0.1.2"
authors = ["Shane Pearman <spearman@github.com>"]

[dependencies]
generic-array = "0.3.1"
num = "0.1.32"
typenum = "1.3.1"

[dev-dependencies]
quickcheck = "0.2.27"
quickcheck_macros = "0.2.26"
