[package]
name = "bit_store"
version = "0.1.3"
authors = ["Shane Pearman <spearman@github.com>"]

[dependencies]
generic-array = "0.8.0"
num = "0.1.37"
typenum = "1.7.0"

[dev-dependencies]
quickcheck = "0.4.1"
quickcheck_macros = "0.4.2"
